### ISSUE TITLE
瀑布流相册-生成时问题

### ISSUE THREAD

**Issue by longshenzhifeijue** [izhaoo/hexo-theme-zhaoo#11]
![image](https://user-images.githubusercontent.com/42776445/88159540-03167c80-cc40-11ea-8424-cee743965d9e.png)
![image](https://user-images.githubusercontent.com/42776445/88159571-0b6eb780-cc40-11ea-9ef3-759319383252.png)
大佬,这个子级目录和index.md和data有什么对应关系吗?看了文档没太明白,

**Comment by longshenzhifeijue** [comment]
我看你的是打开变成图片了,
![image](https://user-images.githubusercontent.com/42776445/88165002-956e4e80-cc47-11ea-8f8a-5b2d482fa1d3.png)
我的还是一级
![image](https://user-images.githubusercontent.com/42776445/88165040-a74ff180-cc47-11ea-90fd-ce75fe88a5c1.png)
需要怎么配置呢
![image](https://user-images.githubusercontent.com/42776445/88165079-b5057700-cc47-11ea-80a3-dffdfe759052.png)

**Comment by izhaoo** [comment]
确实有点难以理解，文档我稍微更新了一下，可以看看：[文档](https://www.izhaoo.com/2020/05/05/hexo-theme-zhaoo-doc/)

稍后我会传一些例子到主题项目中，可以 `clone` 下来看看哦~

**Comment by izhaoo** [comment]
可以参考这边的例子哦：[举个栗子](https://github.com/izhaoo/hexo-theme-zhaoo/tree/master/_example/source)

**Comment by longshenzhifeijue** [comment]
搞好了,多谢大佬的example
