### ISSUE TITLE
hljs类名未注入，导致代码高亮未生效

### ISSUE THREAD

**Issue by xiao-js** [izhaoo/hexo-theme-zhaoo#13]
![image](https://user-images.githubusercontent.com/29617979/88481333-6e888300-cf8d-11ea-8c7c-70fbca8da4bf.png)
![image](https://user-images.githubusercontent.com/29617979/88481367-af809780-cf8d-11ea-91ba-7c73320850d0.png)

**Comment by xiao-js** [comment]
clean一下  重启就好了……

**Comment by izhaoo** [comment]
![屏幕快照 2020-07-26 下午10 32 03](https://user-images.githubusercontent.com/30286980/88481759-dfc93580-cf8f-11ea-9c27-33f5b9e393de.jpg)

Yes，切换主题的话，到配置文件 `CDN`  下替换 `highlight_css` 链接。
