### ISSUE TITLE
希望添加daovoice评论

### ISSUE THREAD

**Issue by olivine1** [izhaoo/hexo-theme-zhaoo#14]
大佬，可以预埋一下daovoice的评论吗，自己配置的话那个聊天按钮会悬浮在屏幕中间。在daovoice后台设置里更改像素值没有什么用，不知道问题出在哪儿了。

**Comment by izhaoo** [comment]
好滴，抽空我加一个哈~

**Comment by olivine1** [comment]
谢谢大佬，麻烦了😊

**Comment by izhaoo** [comment]
`DaoVoice` 即时通讯功能已添加，详见配置说明：

[daovoice 配置](https://www.izhaoo.com/2020/05/05/hexo-theme-zhaoo-doc/#DaoVoice)
