### ISSUE TITLE
TodoList

### ISSUE THREAD

**Issue by izhaoo** [izhaoo/hexo-theme-zhaoo#15]
1. 全站开启 `grid` 布局：栅格化功能实现方式改为 `grid` 布局；瀑布流相册实现方式由 `justfieldGallery` 插件改为 `grid` 布局。
2. 引入 `ES6` 栈：`babel` 、 `npm` 、 `ESLint`，没有模块化支持太痛苦了！
3. 逐步移除 `jQuery`（首先移除相关插件），改为原生方式实现。（实现一个龙鸣版 `Vue` 、 `React`）
4. 性能优化：动画特效优化（性能+效果）、防抖节流。
5. 新特性：增加 `daovoice` 评论支持、增加友情链接、增加文章目录、增加黑夜模式、增加极简阅读模式。
6. 急需优化：侧边目录、菜单（通过右下角 `Fab` 打开反人类了）

**Comment by FuShaoLei** [comment]
建议 换个图片（就是在hexo官网的主题展示的图片），现在这个让人很没用点击的欲望，我建议你换成这样的（或者差不多这样的，我的意思是顶部那个没什么吸引力，往下一点才是亮点）
![](https://cdn.jsdelivr.net/gh/fushaolei/img/20200806164805.png)

另外，主题很好看，加油哦 👍

**Comment by izhaoo** [comment]
> 建议 换个图片（就是在hexo官网的主题展示的图片），现在这个让人很没用点击的欲望，我建议你换成这样的（或者差不多这样的，我的意思是顶部那个没什么吸引力，往下一点才是亮点）
> ![](https://camo.githubusercontent.com/6b2a4bf3345432099fd0f0fb59a906f3fcbac9ab/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f66757368616f6c65692f696d672f32303230303830363136343830352e706e67)
> 
> 另外，主题很好看，加油哦 👍

好滴，感谢你的建议哈~

**Comment by olivine1** [comment]
daovoice在移动端回车无法发出消息，再把浏览器UA改成电脑就没问题了

**Comment by Drrany** [comment]
希望支持代码块字体自定义~以及如果高亮颜色能和hover分开就好了

**Comment by izhaoo** [comment]
> daovoice在移动端回车无法发出消息，再把浏览器UA改成电脑就没问题了

这个是 `DaoVoice` 的问题了，确实手机端不能用。

**Comment by izhaoo** [comment]
> 希望支持代码块字体自定义~以及如果高亮颜色能和hover分开就好了

下个版本引入，自定义字体用 `CDN` 引入？
