### ISSUE TITLE
似乎是渲染有点问题？

### ISSUE THREAD

**Issue by Drrany** [izhaoo/hexo-theme-zhaoo#16]
大部分显示正常但是会有几个还是白的
![image](https://user-images.githubusercontent.com/58012590/90226225-47fb9080-de45-11ea-85f1-3b9a2531b5fc.png)

**Comment by izhaoo** [comment]
MD 源文件可以发一下不，我对照着看一下。

**Comment by Drrany** [comment]
> MD 源文件可以发一下不，我对照着看一下。


[GithubPage-Hexo搭建个人博客记录（主要是一些遇到的坑）.zip](https://github.com/izhaoo/hexo-theme-zhaoo/files/5074088/GithubPage-Hexo.zip)

**Comment by izhaoo** [comment]
确实是个 `Bug`，列表下的标签样式不显示，下个版本修复~

**Comment by Drrany** [comment]
> 确实是个 `Bug`，列表下的标签样式不显示，下个版本修复~

好的~辛苦了
