### ISSUE TITLE
版权声明处文章链接会有超出框的现象

### ISSUE THREAD

**Issue by cuojue11** [izhaoo/hexo-theme-zhaoo#18]
![image](https://user-images.githubusercontent.com/35679523/90334972-0b29c800-e004-11ea-8b95-48c5c0bb5c5c.png)

**Comment by izhaoo** [comment]
我这边测试了一下没问题，方便的话能提供一下你的 `URL` 吗。

**Comment by cuojue11** [comment]
我就是昨天和你聊q那个

**Comment by izhaoo** [comment]
已修复~
