### ISSUE TITLE
社交 icon的更换

### ISSUE THREAD

**Issue by 59lx** [izhaoo/hexo-theme-zhaoo#2]
如题，请问社交相关选项的 icon 如何更换，譬如我想增加一个 twitter 的社交方式，需要其 icon。

**Comment by izhaoo** [comment]
这边icon采用的是阿里的iconfont，可以在iconfont挑选icon加入项目，然后复制css链接加入主题。

**Comment by izhaoo** [comment]
可以加我vx或QQ，方便聊。

**Comment by 59lx** [comment]
ok,感谢
