### ISSUE TITLE
docs : error path of image

### ISSUE THREAD

**Issue by YUbuntu0109** [izhaoo/hexo-theme-zhaoo#20]
❌ [使用文档](https://www.izhaoo.com/2020/05/05/hexo-theme-zhaoo-doc/) 中 `/image/20200421200902.jpg #设置本地图片` 地址写错咯 !

✅ 应该是 : `/images/20200421200902.jpg` ~

**Comment by izhaoo** [comment]
谢谢！可以加入主题示例列表哦~
