### ISSUE TITLE
希望增加 Motto 多行显示功能

### ISSUE THREAD

**Issue by HandwerSTD** [izhaoo/hexo-theme-zhaoo#22]
如题，希望支持换行符 `\n` 换行或多行时默认居中、两边留白
不然可能会出现下面这种情况
![image](https://user-images.githubusercontent.com/37949764/96115497-9eef1600-0f19-11eb-88ae-1d6b94b8af55.png)

最后提前感谢开发者

**Comment by izhaoo** [comment]
安排

**Comment by izhaoo** [comment]
done

**Comment by HandwerSTD** [comment]
好滴，感谢开发者这么快就修复了
