### ISSUE TITLE
头图随机选择功能有时候无法加载

### ISSUE THREAD

**Issue by HandwerSTD** [izhaoo/hexo-theme-zhaoo#25]
如题，`data-original` 里面是空的
![image](https://user-images.githubusercontent.com/37949764/96252859-35d4d480-0fe5-11eb-949c-72660d65c997.png)

**Comment by izhaoo** [comment]
`galleries.json` 方便贴上来看看吧

**Comment by HandwerSTD** [comment]
![image](https://user-images.githubusercontent.com/37949764/96256135-af22f600-0fea-11eb-8520-25ed4635fddb.png)
就长这样

**Comment by HandwerSTD** [comment]
找到问题了，`random-image.js` 随机数好像写错了
```js
var count = images.length;
res = images[Math.floor(Math.random() * (count + 1))];
```
应该为
```js
var count = images.length;
res = images[Math.floor(Math.random() * (count))];
```
我记得这玩意不是下标从 0 开始到 count - 1 的吗……

**Comment by izhaoo** [comment]
> 找到问题了，`random-image.js` 随机数好像写错了
> 
> ```js
> var count = images.length;
> res = images[Math.floor(Math.random() * (count + 1))];
> ```
> 
> 应该为
> 
> ```js
> var count = images.length;
> res = images[Math.floor(Math.random() * (count))];
> ```
> 
> 我记得这玩意不是下标从 0 开始到 count - 1 的吗……

有道理，草率了！马上修复。

**Comment by HandwerSTD** [comment]
好滴，另外我刚刚修锅的时候顺手把自定义图片列表的 feature 加上了，要不然我开个 PR 你看一下？可以留给可能有需要的人用，或者觉得自适应不够完美的时候也可以有个备选方案。

**Comment by izhaoo** [comment]
> 好滴，另外我刚刚修锅的时候顺手把自定义图片列表的 feature 加上了，要不然我开个 PR 你看一下？可以留给可能有需要的人用，或者觉得自适应不够完美的时候也可以有个备选方案。

好滴！万分感谢！
