### ISSUE TITLE
取消文章 post 图片

### ISSUE THREAD

**Issue by 59lx** [izhaoo/hexo-theme-zhaoo#3]
如题，域名解析有点慢，想要把 post 文章图片的功能取消，请问如何操作？

**Comment by izhaoo** [comment]
这个功能暂时没做，后续我会加上，感谢建议。
我考虑是做一套精简版的样式，不带图片，感觉如何？

**Comment by 59lx** [comment]
首页图可以保留，文章 post 图可以考虑去掉弄成精简版~
