### ISSUE TITLE
请问如何让页面中的博客正文加宽？

### ISSUE THREAD

**Issue by lvchentao** [izhaoo/hexo-theme-zhaoo#30]
作者您好，如果在宽屏上使用，发现博客正文的宽度之只占屏幕很小一部分，很多代码都要来回拖动，请问有没有办法设置呢

**Comment by izhaoo** [comment]
这个暂时还不支持，我下个版本写一个自定义宽度。

**Comment by izhaoo** [comment]
已更新，在 `_config.yml` 中配置即可：

# Page Size
post_page_size:
  width: 800px
