### ISSUE TITLE
建议更换下fancybox_js默认的cdn地址

### ISSUE THREAD

**Issue by RayZoey** [izhaoo/hexo-theme-zhaoo#33]
使用现在默认的cdn地址: `https://cdn.bootcss.com/fancybox/3.5.7/jquery.fancybox.min.js`得到的结果不正确，导致除本地图片无法加载，md内的图片不发送访问请求，可以替换为`https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js`

**Comment by izhaoo** [comment]
收到，感谢老铁提醒。
