### ISSUE TITLE
Cannot read property 'enable' of undefined

### ISSUE THREAD

**Issue by ben142857** [izhaoo/hexo-theme-zhaoo#35]
Unhandled rejection TypeError: D:\MyBlog\themes\zhaoo\layout\index.ejs:2
    1| <main id="main">
 >> 2|   <% if (theme.preview.enable === true) { %>
    3|     <%- partial('_partial/index/preview') %>
    4|   <% } %>
    5|   <div class="container" id="container">

Cannot read property 'enable' of undefined

**Comment by izhaoo** [comment]
可以看看 `_config.ynl` 的 `preview` 配置项下面有没有 `enable` 项。

**Comment by ben142857** [comment]
{
  "name": "colorful",  //相册名称
  "cover": "https://pic.izhaoo.com/2020050242.jpg",  //相册封面
  "description": "君未看花时，花与君同寂；君来看花日，花色一时明。",  //相册介绍
  "photos": [  //图片内容
    "https://pic.izhaoo.com/2014031601.jpg",
    "https://pic.izhaoo.com/2017071602.jpg",
    "https://pic.izhaoo.com/2017071603.jpg",
    "https://pic.izhaoo.com/2017072104.jpg"
  ]
}
这个怎么替换成本地图片呢

**Comment by izhaoo** [comment]
直接把 `potos` 里面的地址改成本地地址就可以了，比如 `/images/pic.izhaoo.com/2014031601.jpg` 。

**Comment by ben142857** [comment]
"/images/theme/image001"我用这个地址加载不出来

**Comment by izhaoo** [comment]
应该是图片路径不对，你看一下 `hexo g` 生成后的 `public` 文件夹里面的图片路径有没有对应上。

**Comment by ben142857** [comment]
解决了但是点击图片以后下面显示大图时会出问题瀑布式的会有两块空白区域

**Comment by ben142857** [comment]
如果要像你博客里的一样还需要别的配置吗

**Comment by izhaoo** [comment]
可以截个图看看吗？

**Comment by ben142857** [comment]
![image](https://user-images.githubusercontent.com/55623805/97285195-e14f1600-187c-11eb-88c5-3f9049ef69c2.png)

**Comment by ben142857** [comment]
图片没在原本该在的位置

**Comment by izhaoo** [comment]
应该是 `fancybox` 的 `CDN` 炸了，导致加载不出（奇怪的是我这边是好的），详见这篇 `issues`：

#33

**Comment by ben142857** [comment]
fancybox_css: https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js
是用这个吧

**Comment by izhaoo** [comment]
js 和 css 都改一下吧。

**Comment by ben142857** [comment]
解决了，评论点不开和本轮链接怎么设置呢

**Comment by izhaoo** [comment]
评论需要配置的，可以选择 valine 或 gitalk 开启，教程见我的博客。

**Comment by ben142857** [comment]
文章统计阅读量那个配置里的serverURLs：配的是哪个url

**Comment by izhaoo** [comment]
https://leancloud.cn/

**Comment by ben142857** [comment]
日期的月份怎么设置成中文呢

**Comment by ben142857** [comment]
这样统计的是全站的访问量呀

**Comment by izhaoo** [comment]
这个url只是接口，统计单篇文章的。

系统设置语言 zh-CN

**Comment by ben142857** [comment]
![image](https://user-images.githubusercontent.com/55623805/97514811-9ba06380-19ca-11eb-8591-2a16b3336c2d.png)

**Comment by ben142857** [comment]
![image](https://user-images.githubusercontent.com/55623805/97514841-ae1a9d00-19ca-11eb-9aee-1e26b7777127.png)

**Comment by ben142857** [comment]
我用配置文件里设置这个链接统计的就是全站的刷新一次就加一次文章的怎么回事呢

**Comment by izhaoo** [comment]
不应该吧，你看一下我的example吧。
