### ISSUE TITLE
深色模式下代码高亮颜色问题

### ISSUE THREAD

**Issue by HandwerSTD** [izhaoo/hexo-theme-zhaoo#36]
如题，深色模式下代码高亮不会自动变颜色
![image](https://user-images.githubusercontent.com/37949764/97435908-1716fc00-195c-11eb-993d-799466b2341d.png)

可以考虑在 `themes/zhaoo/layout/_partial/head.ejs` 的代码高亮处加一个判断，但是如何读取 `prefers-color-scheme` 这个我还不大会

**Comment by izhaoo** [comment]
深色模式还在匹配中，暂时会存在一些问题，后续慢慢会修复。

**Comment by HandwerSTD** [comment]
> 深色模式还在匹配中，暂时会存在一些问题，后续慢慢会修复。

或者你试试教我一下怎么读取 `prefers-color-scheme`，我改一改提个 PR

**Comment by izhaoo** [comment]
JS: `window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'`

还是我来改吧，这块我写了一半了，这两天有点事情先搁置一下。

**Comment by HandwerSTD** [comment]
好的，那我等更新吧

**Comment by izhaoo** [comment]
已修复。
