### ISSUE TITLE
这里百度统计出现了两处，而且第一处代码中硬编码 KEY 了

### ISSUE THREAD

**Issue by iaosee** [izhaoo/hexo-theme-zhaoo#38]
https://github.com/izhaoo/hexo-theme-zhaoo/blob/661b3d06d22f7176992c64d0dd25d1b71ab3b16e/layout/_partial/script.ejs#L58

https://github.com/izhaoo/hexo-theme-zhaoo/blob/661b3d06d22f7176992c64d0dd25d1b71ab3b16e/layout/_partial/script.ejs#L65

构建后渲染出来两个，这里应该只使用其中一个吧

**Comment by izhaoo** [comment]
收到反馈，谢谢！
