### ISSUE TITLE
开启动态 Motto, 更改 API 句子类型未生效

### ISSUE THREAD

**Issue by iaosee** [izhaoo/hexo-theme-zhaoo#41]
开启动态 Motto, 更改 preview.motto.api 的参数为 `https://v1.hitokoto.cn/?encode=text&c=i`
这里的参数 `c=i` 为诗句类型，但是获得的句子并非诗句类型

**Comment by iaosee** [comment]
找到原因了，渲染获取的 API 地址被编码了

![image](https://user-images.githubusercontent.com/15712668/98200157-f48e6f80-1f67-11eb-8f85-5f43fae7cdf2.png)

**Comment by izhaoo** [comment]
强啊！！！

**Comment by izhaoo** [comment]
我加个转义

**Comment by iaosee** [comment]
这个我改吧，等会提个PR

**Comment by iaosee** [comment]
> 我加个转义

使用 `https://v1.hitokoto.cn`  api 多参数的话还是会有问题，得写个反转义方法，不知道 hexo 有没有提供

**Comment by izhaoo** [comment]
解决了，是 `ejs` 转义了， `<%=  %>` 改成 `<%-  %>` 即可。

**Comment by iaosee** [comment]
好的 👌 ，强 ！
