### ISSUE TITLE
提案：IM 即时通讯

### ISSUE THREAD

**Issue by izhaoo** [izhaoo/hexo-theme-zhaoo#46]
现默认的 `IM` 模块为 `DaoVoice`，准备接入并支持更多的三方 `IM`，如有需要可以留言。

例如：腾讯兔小巢

**Comment by TomWangKing** [comment]
https://txc.qq.com/

**Comment by TomWangKing** [comment]
接入文档 https://txc.qq.com/helper/WEBGuide
