### ISSUE TITLE
mobile a链接点击出现蓝色方框

### ISSUE THREAD

**Issue by TomWangKing** [izhaoo/hexo-theme-zhaoo#50]
解决方案如下
https://blog.csdn.net/qq_38280315/article/details/78064194

**Comment by izhaoo** [comment]
已修复。

**Comment by TomWangKing** [comment]
div button 还有span也会出现
https://blog.csdn.net/qq_34803821/article/details/85331020

**Comment by izhaoo** [comment]
thank u sir
