### ISSUE TITLE
添加文章目录

### ISSUE THREAD

**Issue by kangshitao** [izhaoo/hexo-theme-zhaoo#51]
希望在侧边栏添加文章目录，有跟随定位的功能，屏幕显示内容对应的标题高亮。

**Comment by HandwerSTD** [comment]
目录好像很早就有计划了，不过一直没找到比较好看的设计，所以到现在还没加

**Comment by kangshitao** [comment]
> 目录好像很早就有计划了，不过一直没找到比较好看的设计，所以到现在还没加

嗯，作者也说了，一直有点问题，所以没发出来，提个issues督促一下他hhh

**Comment by izhaoo** [comment]
安排安排

**Comment by izhaoo** [comment]
已上线，预发布期，欢迎提 `bug`。
