### ISSUE TITLE
请问下,这个置顶该如何操作呢?我哪里配置不对吗

### ISSUE THREAD

**Issue by longshenzhifeijue** [izhaoo/hexo-theme-zhaoo#6]
![image](https://user-images.githubusercontent.com/42776445/85002086-12a92e00-b187-11ea-912e-052b68f04033.png)

**Comment by izhaoo** [comment]
[zhaoo - 主题使用文档](https://www.izhaoo.com/2020/05/05/hexo-theme-zhaoo-doc/)
可以参考这里的【文章置顶】。

**Comment by longshenzhifeijue** [comment]
这个问题好了,非常感谢🙏,再问下,这里导航标签如何配置才会再页面生效呢?
![image](https://user-images.githubusercontent.com/42776445/85008295-5dc73f00-b18f-11ea-8f24-452ad85be79a.png)
![image](https://user-images.githubusercontent.com/42776445/85008316-661f7a00-b18f-11ea-8a3f-3bb10c8d681d.png)

**Comment by longshenzhifeijue** [comment]
藏的有点深😅,我先看下
![image](https://user-images.githubusercontent.com/42776445/85009323-d8448e80-b190-11ea-9942-5ffcbf120961.png)
