### ISSUE TITLE
Motto插件具体应该怎么用呢?

### ISSUE THREAD

**Issue by yannsean** [izhaoo/hexo-theme-zhaoo#7]
顺便提一句作者真的是个文案天才

**Comment by izhaoo** [comment]
`hexo-plugin-motto` 其实现在只是个 `demo`，还没完善。后期打算做一套系统，累死“一言”一样。

[hexo-plugin-motto](https://github.com/izhaoo/hexo-plug-motto)

用法：

1. 在 `motto.txt` 中写入格言，一行一句话。
2. `npm run start` 启动服务。
3. 在主题 `config.yml` 中填写服务的URL即可。

**Comment by yannsean** [comment]
谢谢，用了下一言，感觉挺好

**Comment by izhaoo** [comment]
> 谢谢，用了下一言，感觉挺好

要不我把一言集成进主题？
