### ISSUE TITLE
瀑布流相册-生成时-没有生成对应的gallery子目录

### ISSUE THREAD

**Issue by zcbuaasmea** [izhaoo/hexo-theme-zhaoo#9]
按照您的配置说明文档进阶配置中关于瀑布流的配置，能够生成galleries下index.html，但是没有生成galleries/xxx下对应的gallery子index.html. （另外hexo数据子目录的目录名改为source/_data, 说明文档是/data，当然这里只相应数据注入hexo不影响此处）, 除非我手动在galleries目录下创建与json文件中匹配的文件夹和对应的md才能够生成。
是否有其他配置？

**Comment by izhaoo** [comment]
我说明文档写的不够严谨，造成了歧义，不好意思哈~

1. 子文件夹需要再新建的，可以在 `galleries` 下继续 `hexo new page`。

2. 确实是 `_data`，我说明文档这边泛指了。

**Comment by izhaoo** [comment]
我一会儿更新一下配置文档，感谢大佬提醒~
